"""
generate_walk_test_vectors.py — Generate full kangaroo-walk test cases
from the trusted Python reference (kangaroo_cpu.JumpTable +
kangaroo_walk_sim.solve_sim, both already verified against each other and
against the dict-based baseline).

Deliberately avoids re-deriving JumpTable.build()'s exponent-selection
math (center = round(log2(isqrt(range))), spread, etc.) in C++ -- that
would be a new source of Python/C++ divergence risk for no benefit, since
the table only needs to be computed ONCE per test case and Python already
does it correctly. The exponents are embedded directly as constants; the
GPU only has to compute scalar_mult for each one (already verified in
Phase 4b) and run the walk loop itself (the new, not-yet-hardware-verified
part).
"""

import random
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from secp256k1 import scalar_mult, N
from kangaroo_cpu import JumpTable
from kangaroo_walk_sim import solve_sim

TEST_CASES = [
    (16, 4, 100),
    (18, 4, 100),
    (20, 5, 100),
    (22, 5, 100),
]


def u256_hex_limbs(x: int):
    return [f"0x{(x >> (64*i)) & ((1<<64)-1):016x}ULL" for i in range(4)]


if __name__ == "__main__":
    rng = random.Random(42)  # same seed as kangaroo_cpu.py's own self-test, for continuity
    cases = []

    for bits, dp_bits, seed_offset in TEST_CASES:
        a, b = 1 << (bits - 1), 1 << bits
        range_size = b - a
        k_true = rng.randrange(a, b)
        Q = scalar_mult(k_true)

        table = JumpTable.build(range_size)

        k_recovered, jumps = solve_sim(Q, a, b, dp_bits=dp_bits, max_jumps=2_000_000,
                                        dp_table_capacity=65536)
        assert k_recovered == k_true, f"sim itself failed for bits={bits} -- fix before generating vectors"

        cases.append({
            "bits": bits, "a": a, "b": b, "dp_bits": dp_bits,
            "pubkey_x": Q.x, "pubkey_y": Q.y,
            "exponents": table.exponents,
            "expected_key": k_true,
            "expected_jumps": jumps,
        })
        print(f"bits={bits}: k_true={k_true} jumps_to_solve={jumps} (sim-verified)")

    with open("walk_test_vectors.h", "w") as f:
        f.write("// AUTO-GENERATED by generate_walk_test_vectors.py -- do not hand-edit.\n")
        f.write("// Each test case's jump-table exponents and expected recovered key come\n")
        f.write("// from the trusted Python reference (kangaroo_cpu.JumpTable +\n")
        f.write("// kangaroo_walk_sim.solve_sim, cross-verified against the dict-based\n")
        f.write("// baseline). The GPU only computes the jump POINTS from these exponents\n")
        f.write("// (via already-verified scalar_mult) and runs the walk loop.\n")
        f.write("#pragma once\n#include <cstdint>\n\n")
        f.write(f"#define N_WALK_TESTS {len(cases)}\n")
        f.write(f"#define JUMP_TABLE_SIZE 32\n\n")

        f.write("struct WalkTestCase {\n")
        f.write("    uint64_t a[4];\n")
        f.write("    uint64_t b[4];\n")
        f.write("    int dp_bits;\n")
        f.write("    uint64_t pubkey_x[4];\n")
        f.write("    uint64_t pubkey_y[4];\n")
        f.write("    int exponents[JUMP_TABLE_SIZE];\n")
        f.write("    uint64_t expected_key[4];\n")
        f.write("    uint64_t max_jumps;\n")
        f.write("};\n\n")

        f.write(f"__device__ WalkTestCase WALK_TESTS[{len(cases)}] = {{\n")
        for c in cases:
            f.write("    {\n")
            f.write(f"        {{{', '.join(u256_hex_limbs(c['a']))}}},\n")
            f.write(f"        {{{', '.join(u256_hex_limbs(c['b']))}}},\n")
            f.write(f"        {c['dp_bits']},\n")
            f.write(f"        {{{', '.join(u256_hex_limbs(c['pubkey_x']))}}},\n")
            f.write(f"        {{{', '.join(u256_hex_limbs(c['pubkey_y']))}}},\n")
            f.write(f"        {{{', '.join(str(e) for e in c['exponents'])}}},\n")
            f.write(f"        {{{', '.join(u256_hex_limbs(c['expected_key']))}}},\n")
            f.write(f"        {max(2_000_000, c['expected_jumps'] * 10)}ULL\n")
            f.write("    },\n")
        f.write("};\n")

    print(f"\nWrote walk_test_vectors.h with {len(cases)} test cases.")
