"""
generate_point_test_vectors.py — Generate point_add and scalar_mult test
vectors from the trusted secp256k1.py reference, including deliberately
targeted edge cases (doubling, infinity, P+(-P)==infinity, k=0, k=1,
k=N-1) alongside random cases.
"""

import random
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from secp256k1 import G, N, INFINITY, Point, point_add, point_neg, scalar_mult

N_RANDOM_ADD = 150
N_RANDOM_SCALAR = 80


def u256_hex_limbs(x: int):
    return [f"0x{(x >> (64*i)) & ((1<<64)-1):016x}ULL" for i in range(4)]


def emit_point_arrays(f, prefix, points):
    """Emit X, Y, INF arrays for a list of Point objects."""
    f.write(f"__device__ uint64_t {prefix}_X[{len(points)}][4] = {{\n")
    for p in points:
        x = p.x if p.x is not None else 0
        f.write(f"    {{{', '.join(u256_hex_limbs(x))}}},\n")
    f.write("};\n\n")

    f.write(f"__device__ uint64_t {prefix}_Y[{len(points)}][4] = {{\n")
    for p in points:
        y = p.y if p.y is not None else 0
        f.write(f"    {{{', '.join(u256_hex_limbs(y))}}},\n")
    f.write("};\n\n")

    f.write(f"__device__ int {prefix}_INF[{len(points)}] = {{")
    f.write(", ".join("1" if p.is_infinity else "0" for p in points))
    f.write("};\n\n")


def emit_scalar_array(f, name, scalars):
    f.write(f"__device__ uint64_t {name}[{len(scalars)}][4] = {{\n")
    for s in scalars:
        f.write(f"    {{{', '.join(u256_hex_limbs(s))}}},\n")
    f.write("};\n\n")


if __name__ == "__main__":
    rng = random.Random(2468)

    # ---- point_add test vectors ----
    p1_list, p2_list, expected_list = [], [], []

    # Edge case: doubling (P1 == P2)
    P = scalar_mult(rng.randrange(1, N))
    p1_list.append(P); p2_list.append(P); expected_list.append(point_add(P, P))

    # Edge case: P + (-P) == infinity
    P = scalar_mult(rng.randrange(1, N))
    negP = point_neg(P)
    p1_list.append(P); p2_list.append(negP); expected_list.append(point_add(P, negP))

    # Edge case: P + infinity == P, infinity + P == P
    P = scalar_mult(rng.randrange(1, N))
    p1_list.append(P); p2_list.append(INFINITY); expected_list.append(point_add(P, INFINITY))
    p1_list.append(INFINITY); p2_list.append(P); expected_list.append(point_add(INFINITY, P))

    # Edge case: infinity + infinity == infinity
    p1_list.append(INFINITY); p2_list.append(INFINITY); expected_list.append(point_add(INFINITY, INFINITY))

    # Edge case: G + G (a specific, independently-checkable doubling)
    p1_list.append(G); p2_list.append(G); expected_list.append(point_add(G, G))

    # Random distinct-point additions
    for _ in range(N_RANDOM_ADD):
        k1 = rng.randrange(1, N)
        k2 = rng.randrange(1, N)
        P1 = scalar_mult(k1)
        P2 = scalar_mult(k2)
        p1_list.append(P1)
        p2_list.append(P2)
        expected_list.append(point_add(P1, P2))

    # ---- scalar_mult test vectors ----
    scalars, scalar_expected = [], []

    # Known-answer edge cases
    for k in [0, 1, 2, N - 1]:
        scalars.append(k)
        scalar_expected.append(scalar_mult(k))

    # The actual solved puzzle #135 key, as an independent known-answer
    # check beyond synthetic values (matches Phase 0's own known-answer test).
    k135 = 0x6d9392a16883f90903d5f78da57af07eb2
    scalars.append(k135)
    scalar_expected.append(scalar_mult(k135))

    for _ in range(N_RANDOM_SCALAR):
        k = rng.randrange(1, N)
        scalars.append(k)
        scalar_expected.append(scalar_mult(k))

    with open("point_test_vectors.h", "w") as f:
        f.write("// AUTO-GENERATED by generate_point_test_vectors.py -- do not hand-edit.\n")
        f.write("#pragma once\n#include <cstdint>\n\n")
        f.write(f"#define N_ADD_TESTS {len(p1_list)}\n")
        f.write(f"#define N_SCALAR_TESTS {len(scalars)}\n\n")

        emit_point_arrays(f, "ADDT_P1", p1_list)
        emit_point_arrays(f, "ADDT_P2", p2_list)
        emit_point_arrays(f, "ADDT_EXPECTED", expected_list)

        emit_scalar_array(f, "SCALARS", scalars)
        emit_point_arrays(f, "SCALAR_EXPECTED", scalar_expected)

    print(f"Wrote point_test_vectors.h with {len(p1_list)} point_add tests "
          f"({6} targeted edge cases + {N_RANDOM_ADD} random) and "
          f"{len(scalars)} scalar_mult tests ({5} known-answer + {N_RANDOM_SCALAR} random).")
