"""
generate_test_vectors.py — Generate known-answer test vectors from the
TRUSTED secp256k1.py reference, to embed in the CUDA test harness. This
is how correctness gets verified without me being able to compile or run
CUDA myself: the GPU computes these same values, and the host code
compares against ground truth computed here in Python.
"""

import random
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from secp256k1 import P

N_MUL_VECTORS = 2000
N_INV_VECTORS = 200
N_ADD_VECTORS = 500
N_SUB_VECTORS = 500

def u256_hex_limbs(x: int):
    """Return 4 little-endian 64-bit limbs as hex strings, matching the
    CUDA u256 struct's limb[0..3] layout (limb[0] = least significant)."""
    return [f"0x{(x >> (64*i)) & ((1<<64)-1):016x}ULL" for i in range(4)]


def emit_array(f, name, values):
    # NOTE: deliberately __device__ (global memory), NOT __constant__.
    # CUDA's __constant__ memory is capped at 64KB total on essentially
    # all NVIDIA GPUs including the RTX 3080 -- these test vector arrays
    # alone total ~294KB (2000 mul vectors x 3 arrays x 32 bytes, plus
    # add/sub/inv), which would fail to compile or exceed the constant
    # memory budget. __constant__ is the right choice for small,
    # frequently-broadcast read-only data like the actual jump table
    # (a few KB) in the real kernel -- not for bulk test data like this.
    f.write(f"__device__ uint64_t {name}[{len(values)}][4] = {{\n")
    for v in values:
        limbs = u256_hex_limbs(v)
        f.write(f"    {{{', '.join(limbs)}}},\n")
    f.write("};\n\n")


if __name__ == "__main__":
    rng = random.Random(777)

    mul_a, mul_b, mul_expected = [], [], []
    for _ in range(N_MUL_VECTORS):
        a = rng.randrange(0, P)
        b = rng.randrange(0, P)
        mul_a.append(a)
        mul_b.append(b)
        mul_expected.append((a * b) % P)

    add_a, add_b, add_expected = [], [], []
    for _ in range(N_ADD_VECTORS):
        a = rng.randrange(0, P)
        b = rng.randrange(0, P)
        add_a.append(a)
        add_b.append(b)
        add_expected.append((a + b) % P)

    sub_a, sub_b, sub_expected = [], [], []
    for _ in range(N_SUB_VECTORS):
        a = rng.randrange(0, P)
        b = rng.randrange(0, P)
        sub_a.append(a)
        sub_b.append(b)
        sub_expected.append((a - b) % P)

    inv_a, inv_expected = [], []
    for _ in range(N_INV_VECTORS):
        a = rng.randrange(1, P)
        inv_a.append(a)
        inv_expected.append(pow(a, P - 2, P))

    with open("test_vectors.h", "w") as f:
        f.write("// AUTO-GENERATED by generate_test_vectors.py -- do not hand-edit.\n")
        f.write("// Ground truth computed by Python's arbitrary-precision pow()/mod,\n")
        f.write("// which is trusted independently of anything being tested here.\n")
        f.write("#pragma once\n#include <cstdint>\n\n")

        f.write(f"#define N_MUL_VECTORS {N_MUL_VECTORS}\n")
        f.write(f"#define N_ADD_VECTORS {N_ADD_VECTORS}\n")
        f.write(f"#define N_SUB_VECTORS {N_SUB_VECTORS}\n")
        f.write(f"#define N_INV_VECTORS {N_INV_VECTORS}\n\n")

        emit_array(f, "MUL_A", mul_a)
        emit_array(f, "MUL_B", mul_b)
        emit_array(f, "MUL_EXPECTED", mul_expected)

        emit_array(f, "ADD_A", add_a)
        emit_array(f, "ADD_B", add_b)
        emit_array(f, "ADD_EXPECTED", add_expected)

        emit_array(f, "SUB_A", sub_a)
        emit_array(f, "SUB_B", sub_b)
        emit_array(f, "SUB_EXPECTED", sub_expected)

        emit_array(f, "INV_A", inv_a)
        emit_array(f, "INV_EXPECTED", inv_expected)

    print(f"Wrote test_vectors.h with {N_MUL_VECTORS} mul, {N_ADD_VECTORS} add, "
          f"{N_SUB_VECTORS} sub, {N_INV_VECTORS} inv test vectors.")
